##### What is PyTorch?

It's a Python-based scientific computing package targeted at two sets of audiences:

- a replacement for NumPy to use the power of GPUs
- a deep learning research platform that provides maximum flexibility and speed

##### Getting Started

Tensors

Tensors are similar to NumPy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function

In [2]:
import torch

Construct a 5 by 3 matrix, uninitialized:

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


Construct a randomly initialized matrix

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0401, 0.0766, 0.3739],
        [0.7990, 0.2166, 0.5445],
        [0.4735, 0.0562, 0.0490],
        [0.7221, 0.4779, 0.2353],
        [0.7237, 0.7719, 0.9671]])


Construct a matrix filled zeros and of dtype long

In [5]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [7]:
x = x.new_ones(5, 3, dtype = torch.double)             # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype = torch.float)           # override dtype!
print(x)                                               # result has the same size

tensor([[-0.9796, -0.5890, -1.4990],
        [ 0.1997,  0.7467, -0.0324],
        [-0.0719,  0.7676,  0.2132],
        [-1.8763, -0.6821, -0.6764],
        [-0.9862,  2.0848, -1.3410]])


Get its size

In [9]:
print(x.size())

torch.Size([5, 3])


###### torch.Size is in fact a tuple, so it supports all tuple operations.

##### Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.8910, -0.0913, -1.3499],
        [ 0.4791,  1.2895,  0.0012],
        [ 0.6334,  1.1144,  1.2062],
        [-1.7604, -0.1735, -0.0447],
        [-0.0980,  2.7069, -1.1779]])


Addition: syntax 2

In [11]:
print(torch.add(x, y))

tensor([[-0.8910, -0.0913, -1.3499],
        [ 0.4791,  1.2895,  0.0012],
        [ 0.6334,  1.1144,  1.2062],
        [-1.7604, -0.1735, -0.0447],
        [-0.0980,  2.7069, -1.1779]])


Addition: providing an output tensor as argument

In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[-0.8910, -0.0913, -1.3499],
        [ 0.4791,  1.2895,  0.0012],
        [ 0.6334,  1.1144,  1.2062],
        [-1.7604, -0.1735, -0.0447],
        [-0.0980,  2.7069, -1.1779]])


Addition: in-place

In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.8910, -0.0913, -1.3499],
        [ 0.4791,  1.2895,  0.0012],
        [ 0.6334,  1.1144,  1.2062],
        [-1.7604, -0.1735, -0.0447],
        [-0.0980,  2.7069, -1.1779]])


###### Any operation that mutates a tensor in-place is post-fixed with an _. For example:

###### x.copy_(y), x.t_(), will change x.

You can use standard NumPy-like indexing with all bells and whistles!

In [14]:
print(x[:, 1])

tensor([-0.5890,  0.7467,  0.7676, -0.6821,  2.0848])


Resizing: If you want to resize/reshape tensor, you can use torch.view

In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)                             # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use .item() to get the value as a Python number

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.9361])
1.9360841512680054


###### Read later:

100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described https://pytorch.org/docs/stable/torch.html# 

##### Numpy Bridge

Converting a Torch Tensor to a NumPy array and vice-versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array

In [17]:
a = torch.ones(5)

In [18]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b = a.numpy()

In [20]:
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor

See how the np array changed the Torch Tensor automatically

In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

###### CUDA Tensors

Tensors can be moved onto any device using the .to method.

In [23]:
# let us run this cell only if CUDA is available
# We will use "torch.device" objects to move tensors in and out of GPU

if torch.cuda.is_available():
    device = torch.device("cuda")                   # a CUDA device object
    y = torch.ones_like(x, device = device)         # directly create a tensor on GPU
    x = x.to(device)                                # or just use strings
    '''.to("cuda")'''
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))                # ''.to'' can also change dtype
    '''together!'''